:sparkles: [Feat]: 항목 API 구현
Timify-repo/Timify-server pull request #46
Opened 2024-07-11 09:58 UTC by BaekJaehyuk

## 🚀 개요
항목 API 구현

## 🔍 변경사항
- 구조 변경

## ⏳ 작업 내용
- [ ] 항목 등록
- [ ] 항목 삭제
- [ ] 항목 조회
- [ ] 항목 순서 변경

### 📝 논의사항
코드 관련 질문 남겨주시면 감사하겠습니다 :)

2024-07-11 11:39 UTC, GwonDooHyeon commented on src/main/java/timify/com/subject/SubjectService.java
getSubjectAll 메소드는 메소드명을 보아 조회를 하는 메소드로 보이는데,
@Transactional(readOnly = true) 가 있어야 되지 않을까요 ?!

2024-07-11 11:39 UTC, GwonDooHyeon commented on src/main/java/timify/com/subject/domain/Subject.java
private int order_num; 
- 단순 타이핑 실수하신것 같은데, 카멜케이스로 변경하는게 어떨까요 ~?

2024-07-11 11:39 UTC, GwonDooHyeon commented on src/main/java/timify/com/subject/SubjectService.java
고생하셨습니다 ~

2024-07-11 15:07 UTC, Eunjin3395 requested changes
추가로, 항목 이름 수정에 대한 api 도 필요할 것 같습니다. 기능명세서에는 적혀있는데 api 명세할 때 빠진 것 같아요..!

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    int orderNum = subjectRepository.countByMember(findMember) + 1;
subject가 status가 INACTIVE인 경우에는 order num을 매기는 것에서 제외 해야할 것 같아요. 단순히 member로만 count하면 안될 것 같습니다

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    Subject registerSubject = subjectRepository.save(SubjectConverter.toSubject(request, findMember, orderNum));
여기에서 subject -> member의 연관관계는 converter에서 설정이 되었는데, member -> subject 연관관계를 맺어주는 부분이 없습니다. member 엔티티가 List<subject> 를 갖고 있기 때문에 member -> subject로의 연관관계 매핑 부분도 필요합니다..!

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/dto/SubjectRequest.java
> +    String title;
title이 "" 일 때에 대한 검증이 필요할 것 같습니다..!

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    List<subjectInfoDto> subjectListAll = subjectRepository.findAllByMember(findMember).stream()
여기에서도 subject의 status를 고려하지 않고 member id로 subject를 모두 불러오게 되어서, INACTIVE 상태인 subject들도 모두 조회가 될 것 같습니다

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +  public subjectInfoDto registerSubject(@Valid SubjectRequest.registerSubjectRequest request) {
항목 등록에 개수 제한은 혹시 없는 것일까요?

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    List<Subject> subjects = subjectRepository.findAllByMember(member);
여기서도 status도 조회 조건으로 추가가 필요할 것 같아요

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    subjects.forEach(s -> {
그럼 만약 5번째였던 subject를, newOrderNum 2로 순서 변경 요청을 한 경우, 2번째 subject <-> 5번째 subject 이렇게 서로 교체가 되는 것일까요?

2024-07-11 15:07 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/domain/Subject.java
> +    public void updateOrderNum(int newOrderNum) {
@Setter로 구현해도 괜찮을 것 같습니다!

2024-07-11 15:28 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    subjects.forEach(s -> {
맞습니다 :)

2024-07-11 15:29 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
놓친 부분 체크해 주셔서 감사합니다 :)

2024-07-11 15:29 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/domain/Subject.java
감사합니다 :)

2024-07-11 15:31 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/domain/Subject.java
> +    public void updateOrderNum(int newOrderNum) {
Entity에 @Setter의 사용을 지양하라는 글을 읽은 적이 있습니다

https://velog.io/@langoustine/setter-%EC%A7%80%EC%96%91-%EC%9D%B4%EC%9C%A0 

이 글 확인해 주시고 해당 부분 논의해보면 좋을 듯 싶습니다 !

2024-07-11 15:32 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    List<Subject> subjects = subjectRepository.findAllByMember(member);
수정하겠습니다 : )

2024-07-11 15:32 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +  public subjectInfoDto registerSubject(@Valid SubjectRequest.registerSubjectRequest request) {
항목 등록 개수 제한해서 관련 로직을 구현하지 않았는데 혹시 요구 사항에 적혀져 있었나요?

2024-07-11 15:32 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    List<subjectInfoDto> subjectListAll = subjectRepository.findAllByMember(findMember).stream()
해당 부분은 빠른 시일 내로 수정하겠습니다.

2024-07-11 15:46 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/dto/SubjectRequest.java
> +    String title;
감사합니다 :)

2024-07-11 15:57 UTC, GwonDooHyeon reviewed
ㅇ

2024-07-11 15:57 UTC, GwonDooHyeon commented on src/main/java/timify/com/subject/SubjectController.java
> +    getListDto subjectList = subjectService.getSubjectAll();
테스트 리뷰입니다

2024-07-11 16:31 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
감사합니다 : )

2024-07-11 16:31 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    Subject registerSubject = subjectRepository.save(SubjectConverter.toSubject(request, findMember, orderNum));
확인했습니다.

2024-07-12 07:18 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    int orderNum = subjectRepository.countByMember(findMember) + 1;
확인했습니다 : )

2024-07-12 10:08 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +  public subjectInfoDto registerSubject(@Valid SubjectRequest.registerSubjectRequest request) {
아아 적혀있었는지는 모르겠는데,, 저는 공부 방법/분류/장소 등록할 때 기획자님이 개수 제한 15개로 두신다고 하셨어서 혹시 항목에도 개수 제한이 있는건가 싶었어요

2024-07-12 10:09 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/domain/Subject.java
> +    public void updateOrderNum(int newOrderNum) {
앗 네네 그럼 저도 그냥 setter 말고 update 메소드를 별도로 만드는 것으로 수정하겠습니다

2024-07-13 08:47 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +  public subjectInfoDto registerSubject(@Valid SubjectRequest.registerSubjectRequest request) {
15개 제한을 두는 것으로 구현 완료했습니다.

2024-07-13 09:21 UTC, Eunjin3395 requested changes

2024-07-13 09:21 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    subject.updateTitle(request.getTitle());
기능명세서에 보니까 항목 이름은 중복 불가인 것 같아요! 이름 중복 여부 검증 추가 필요할 것 같습니다

2024-07-13 09:21 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +
항목 이름의 중복 여부 검증도 필요할 것 같습니다!

2024-07-13 09:47 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    subject.updateTitle(request.getTitle());
기능명세서 다시 한 번 확인하겠습니다. 수정하겠습니다.

2024-07-13 09:48 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +
감사합니다 : ) 수정하겠습니다

2024-07-13 12:40 UTC, Eunjin3395 requested changes

2024-07-13 12:40 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    if (subjectRepository.existsByMemberAndTitle(getMember(), request.getTitle())) {
이 중복 검증 로직이 
subject.updateTitle(request.getTitle());
이 코드보다 먼저 실행되어야 할 것 같습니다.....!

2024-07-13 12:52 UTC, baekjaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    if (subjectRepository.existsByMemberAndTitle(getMember(), request.getTitle())) {
예외가 발생하면 @Transactional 어노테이션이 롤백시켜서 기능 상에 문제가 없다고 판단했는데 코드 가독성 때문에 말씀해 주신걸까요?

2024-07-13 12:54 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
> +    if (subjectRepository.existsByMemberAndTitle(getMember(), request.getTitle())) {
앗 아뇨 그런데 title을 업데이트 하고 나서 바로 db에 그 title로 된 subject가 있는지 조회하면 항상 exist true가 나오지 않나 해서요..!

2024-07-13 12:56 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
> +    if (subjectRepository.existsByMemberAndTitle(getMember(), request.getTitle())) {
말씀해 주신 부분 수정했습니다 : )

2024-07-13 12:56 UTC, Eunjin3395 approved these changes
고생하셨습니다!

2024-07-13 14:04 UTC, merged