[Feature/48]: 보관함 API 구현
Timify-repo/Timify-server pull request #52
Opened 2024-07-16 19:16 UTC by BaekJaehyuk

## 🚀 개요
보관함 API 구현, 

## 🔍 변경사항
- API endPoint 수정, API 설계서 수정 완료

## ⏳ 작업 내용
- [ ] 홈으로 항목 이동 API 구현
- [ ] 보관함으로 항목 이동 API 구현 
- [ ] 보관 항목 조회 API 구현

### 📝 논의사항
보관함 API까지 설계하여 Subject Controller는 마무리하였고, 할 일 API 구현하기 전에 리팩토링 및 은진님과 코드 컨벤션 통일하고 진행하겠습니다.

2024-07-18 08:30 UTC, Eunjin3395 requested changes
혹시 재혁님은 코드 컨벤션 네이버랑 구글 중에 어떤거 쓰고 계신가요?

2024-07-18 08:30 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectController.java
> +  public ApiResponse<Long> storeSubject(@PathVariable Long id) {
```suggestion
    @PostMapping("/type/{studyTypeId}/update")
    @Operation(summary = "공부 분류 수정 API", description = "특정 공부 분류의 이름을 수정하는 API 입니다.")
    @Parameters(value = {
            @Parameter(name = "studyTypeId", description = "공부 분류의 id 입니다.")
    })
    public ApiResponse<StudyResponse.studyTypeDto> updateStudyType(
```
path variable이 있는 경우에는 위 처럼 @Parameters를 이용해서 매핑을 해주어야 스웨거에서 테스트가 가능합니다..!

2024-07-18 08:30 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectController.java
> +  public ApiResponse<Long> storeSubject(@PathVariable Long id) {
```suggestion
    public ApiResponse<Long> storeSubject(@PathVariable(name = "id") Long id) {
```
그리고 pathVariable도 웬만해서는 (name="id")를 붙여서 매핑을 정확하게 지정해주는게 좋은 것 같아요..! 테스트해보니까 저는 
Name for argument of type [java.lang.Long] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.] with root cause 
이런 에러가 뜨더라구요..

2024-07-18 08:30 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectController.java
> +  @Operation(summary = "보관함 조회 API", description = "보관된 항목 조회하는 API 입니다.")
이 항목 조회 api를 active / inactive인 상태 따로따로 api를 두지 않고, 그냥 GET /v1/subject에다가 쿼리 스트링으로 status=active, status=inactive 이렇게 받아도 좋을 것 같아요. 컨트롤러 + 서비스 메소드는 하나로 통일하고 repository에서 조회 할 때 status만 다른 값을 넣어주도로 하면 좋을 것 같습니다!

2024-07-18 08:30 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectController.java
컨트롤러에서 @AuthMember로 멤버 엔티티를 받아올 수 있게 변경되어서 이 부분 반영하셔서 컨트롤러&서비스 코드 수정해주시면 될 것 같습니다 !

2024-07-18 08:30 UTC, Eunjin3395 commented on src/main/java/timify/com/subject/SubjectService.java
그리고 지금 항목 삭제와 항목 이름 수정이 상태가 ACTIVE인 항목만 가능하도록 되어 있는데, 피그마에는 보관함에 있는 항목도 삭제가 가능하도록 되어 있습니다..! 보관함에 있는 항목의 이름 수정도 가능한지는 피그마에 명확하게 나와있지 않은데, 이 부분은 기획자님께 확인 후 수정이 필요할 것 같습니다

2024-07-19 11:31 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectController.java
> +  public ApiResponse<Long> storeSubject(@PathVariable Long id) {
확인했습니다.

2024-07-19 11:31 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectController.java
리팩토링하면서 수정하겠습니다.

2024-07-19 13:12 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectController.java
> +  @Operation(summary = "보관함 조회 API", description = "보관된 항목 조회하는 API 입니다.")
해당 부분도 리팩토링 진행하면서 추가하도록 하겠습니다.

2024-07-19 13:12 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectService.java
확인하였습니다.

2024-07-19 14:41 UTC, BaekJaehyuk commented on src/main/java/timify/com/subject/SubjectController.java
> +  public ApiResponse<Long> storeSubject(@PathVariable Long id) {
확인하였습니다.

2024-07-19 15:49 UTC, merged