[Feature/55]: 할 일 API 구현 (등록, 삭제, 조회, 복사)
Timify-repo/Timify-server pull request #62
Opened 2024-07-26 06:20 UTC by BaekJaehyuk

## 🚀 개요
할 일 API 구현 (등록, 삭제, 조회, 복사)
## 🔍 변경사항

- 할 일 API  (등록, 삭제, 조회, 복사) 구현
- Error Stauts / Success Status 변경
- Controller Interface 추가
## ⏳ 작업 내용
- [ ] 할 일 등록 API
- [ ] 할 일 삭제 API
- [ ] 할 일 조회 API
- [ ] 할 일 복사 API

### 📝 논의사항
1. 할 일 이동 API는 변경될 수 있다고 전달 받아 추후에 기능 추가하도록 하겠습니다.

2024-07-26 08:00 UTC, Eunjin3395 requested changes

2024-07-26 08:00 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/controller/TodoController.java
> +    @Operation(summary = "할 일 등록 API", description = "할 일 등록 API 입니다.")
여기에도 @Parameter 추가 해주세요 !

2024-07-26 08:00 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/TodoService.java
> +        StudyType studyType = validateStudyType(request.getStudyTypeId());
studyType, method, place가 해당 회원의 것이 맞는지에 대해서도 검증해야할 것 같습니다 !

2024-07-26 08:00 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/dto/TodoResponse.java
> +        Long studyPlaceId;
이 부분에다가 각각의 name까지 같이 반환 하는게 좋을 것 같아요 ! 어차피 화면에서는 각각의 이름이 보여야하니,,
그리고 피그마 1-1-A 할일 목록에서 필요한 데이터들을 어떻게 응답해줄지,, 같이 추가로 의논해보면 좋을 것 같아요

2024-07-26 08:00 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/TodoService.java
> +        validateSubjectIsActive(subject);
그럼 보관함에 들어간 항목 아래에 있던 할일들은 수정이 불가한 것 맞나요?

2024-07-26 08:00 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/TodoService.java
> +        Subject subject = findSubjectById(subjectId);
여기서 subjectId는 사용자가 요청을 보낸 id인데, 만약 해당 todo의 subject의 id와 이 요청으로 보낸 subjectId가 다를 경우엔 어떻게 되는건가요? 차라리 subjectId를 사용자로부터 받지 않고, todo.subject로 접근해서 쓰는건 어떨까요?

2024-07-26 08:00 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/TodoService.java
> +        findSubjectById(subjectId);
여기서 subjectId를 사용자로부터 받아와야할 필요가 있는지 궁금합니다..!

2024-07-26 08:00 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/TodoService.java
> +            newTodo.associateSubject(subject);
지금 여기서도 사용자가 보낸 subjectId와, existingTodo가 갖고 있던 subjectId가 다른 경우, 둘 중 어떤 subject에 대한 todo가 생성되는 것일까요? 만약 할일 복사가 항목1의 할일A -> 항목1의 할일A' 로만 복사가 가능하고, 항목1의 할일A -> 항목2의 할일A' 이렇게 항목이 달라지는 복사는 안된다고 한다면, 사용자에게서 굳이 subjectId를 받을 필요가 없을 것 같습니다..!

2024-07-26 08:02 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/TodoService.java
> +        validateSubjectIsActive(subject);
넵 맞습니다 :)

2024-07-26 08:04 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/controller/TodoController.java
> +    @Operation(summary = "할 일 등록 API", description = "할 일 등록 API 입니다.")
감사합니다.

2024-07-26 08:07 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/dto/TodoResponse.java
> +        Long studyPlaceId;
넵 알겠습니다 !

2024-07-26 08:12 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/TodoService.java
> +        StudyType studyType = validateStudyType(request.getStudyTypeId());
넵 알겠습니다.

2024-07-26 08:14 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/TodoService.java
> +        findSubjectById(subjectId);
위와 동일하게 로직 처리하면 필요 없다고 생각이 드는데 다시 한 번 수정해보겠습니다.

2024-07-26 08:14 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/TodoService.java
> +        Subject subject = findSubjectById(subjectId);
고민하고 로직 수정하겠습니다.

2024-07-26 08:22 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/TodoService.java
> +            newTodo.associateSubject(subject);
확인했습니다 : )

2024-07-26 12:21 UTC, Eunjin3395 approved these changes
고생하셨습니다 ~

2024-07-26 12:21 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/TodoService.java
> +        Subject subject = subjectRepository.findById(subjectId)
이 subject가 해당 member의 것이 맞는지 검증 추가 필요합니다!

2024-07-26 12:21 UTC, Eunjin3395 commented on src/main/java/timify/com/todo/TodoService.java
>      public Todo insertTodo(Member member, Long subjectId, @Valid todoRequest request) {
service 메소드에는 dto에 @Valid 안 붙여도 되는걸로 알고 있어요..!

2024-07-26 12:26 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/TodoService.java
> +        Subject subject = subjectRepository.findById(subjectId)
추가하겠습니다 :  )

2024-07-26 12:27 UTC, BaekJaehyuk commented on src/main/java/timify/com/todo/TodoService.java
>      public Todo insertTodo(Member member, Long subjectId, @Valid todoRequest request) {
저도 그렇게 알고 있었는데; 인텔리제이가 자동으로 완성해줘서 추가하더라구요. 해당 부분 확인 후에 수정하겠습니다.

2024-07-27 05:32 UTC, Eunjin3395 approved these changes

2024-07-27 05:32 UTC, merged