[Refactor/95] 요구사항 변경으로 인한  코드 리팩토링
Timify-repo/Timify-server pull request #96
Opened 2024-08-30 14:08 UTC by BaekJaehyuk

## 🚀 개요

1. 할 일 수정 API, 일부분 수정이 가능하도록 변경
2. 몰입도 수정 API, 일부부 수정이 가능하도록 변경

## 🔍 변경사항

- Todo Request 요청값 null 체크에 따른 로직 변경
- StudyTime Request 요청값 null 체크에 따른 로직 변경

## ⏳ 작업 내용
- [ ] Todo 관련 DTO, SERVICE 일부 코드 변경
- [ ] StudyTime 관련 DTO, SERVICE 일부 코드 변경

### 📝 논의사항

2024-08-30 14:50 UTC, Eunjin3395 requested changes

2024-08-30 14:50 UTC, Eunjin3395 commented on src/main/java/timify/com/studytime/dto/StudyTimeRequest.java
> +        @NotBlankJsonNullable
혹시 이 어노테이션을 쓰신 이유가 무엇일까요..?! 이건 제가 만든 어노테이션인데 JsonNullable type을 대상으로 NotBlank 검증을 해주는 기능입니다..! 지금 몰입시간 기록 수정 API startTime, endTime에 " " 공백 string을 요청하면 공백 검증이 되지 않아서 에러가 발생합니다...!

2024-08-30 14:50 UTC, Eunjin3395 commented on src/main/java/timify/com/studytime/dto/StudyTimeRequest.java
>      public static class studyTimeRequest {
그리고 지금 studyTimeRequest를 몰입 시간 등록, 수정 API에서 같이 쓰고 있는데 몰입 시간 등록 시에는 startTime, endTime, grade 모두 null도 아니어야하고, 공백도 아니어야 해서 이런 경우엔 request dto를 두개로 나눠서 각각 다른 검증 어노테이션을 붙이는 게 좋을 것 같아요

2024-08-30 14:52 UTC, BaekJaehyuk commented on src/main/java/timify/com/studytime/dto/StudyTimeRequest.java
>      public static class studyTimeRequest {
나눠서 검증 어노테이션을 붙이려고 할려했는데 공통 메서드들이 너무 많아서 로직 변경이 너무 많이 일어날 거 같아 이에 대해 얘기 나눠봐야할 것 같아요

2024-08-30 14:53 UTC, BaekJaehyuk commented on src/main/java/timify/com/studytime/dto/StudyTimeRequest.java
> +        @NotBlankJsonNullable
null 값을 받아야 해서 해당 어노테이션 사용했습니다 ! 아래 말씀해 주신 부분과 같이 이어지는 내용입니다. 그래서 공백 검증 로직을 따로 추가하는 방법도 고려해봐야할 것 같습니다

2024-08-31 03:24 UTC, Eunjin3395 approved these changes
고생하셨습니다!

2024-08-31 03:44 UTC, merged